### ISSUE TITLE
DEP_WEBPACK_COMPILATION_ASSETS ( Masalah Html-webpack-plugin version )

### ISSUE THREAD

**Issue by Rickkun11** [arief-github/progressive-sports-webapp#36]
(node:10164) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by darmawan06** [comment]
Terjadi karena library webpack-manifest, install manifest dengan manual menjadi solusi untuk bug ini.
